### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Smallinger** [anasrar/Zippy-DL#4]
I think there is a better way to tell, the user that the file is expired
```
⏳  Get Page From : http://www19.zippyshare.com/v/FAbGhbHz/file.html
✅  Done
⏳  Fetch Link Download...
(node:8843) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '1' of null
    at Object.exports.GetLink (/usr/lib/node_modules/zippydl/app.js:39:88)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:8843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by anasrar** [comment]
![image](https://user-images.githubusercontent.com/38805204/64407425-7954d380-d0ae-11e9-938b-4d718a17f84a.png)
done
